# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
# 
# Discord: https://discord.gg/papermc
# IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper ) 
# Website: https://papermc.io/ 
# Docs: https://paper.readthedocs.org/ 

verbose: false
config-version: 22
settings:
  use-display-name-in-quit-message: false
  fix-entity-position-desync: true
  incoming-packet-spam-threshold: 300
  lag-compensate-block-breaking: true
  load-permissions-yml-before-plugins: true
  region-file-cache-size: 256
  use-alternative-luck-formula: false
  save-empty-scoreboard-teams: false
  track-plugin-scoreboards: false
  console-has-all-permissions: false
  enable-player-collisions: true
  suggest-player-names-when-null-tab-completions: true
  max-joins-per-tick: 3
  bungee-online-mode: true
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  send-full-pos-for-hard-colliding-entities: true
  unsupported-settings:
    allow-headless-pistons: false
    allow-piston-duplication: false
    allow-permanent-block-break-exploits: false
    allow-headless-pistons-readme: This setting controls if players should be able
      to create headless pistons.
    allow-piston-duplication-readme: This setting controls if player should be able
      to use TNT duplication, but this also allows duplicating carpet, rails and potentially
      other items
    allow-permanent-block-break-exploits-readme: This setting controls if players
      should be able to break bedrock, end portals and other intended to be permanent
      blocks.
  spam-limiter:
    recipe-spam-increment: 1
    recipe-spam-limit: 20
    tab-spam-increment: 1
    tab-spam-limit: 500
  chunk-loading:
    min-load-radius: 2
    max-concurrent-sends: 2
    autoconfig-send-distance: true
    target-player-chunk-send-rate: 100.0
    global-max-chunk-send-rate: -1.0
    enable-frustum-priority: false
    global-max-chunk-load-rate: 300.0
    player-max-concurrent-loads: 4.0
    global-max-concurrent-loads: 500.0
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  item-validation:
    display-name: 8192
    loc-name: 8192
    lore-line: 8192
    book:
      title: 8192
      author: 8192
      page: 16384
  async-chunks:
    threads: -1
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
  loggers:
    deobfuscate-stacktraces: true
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  console:
    enable-brigadier-highlighting: true
    enable-brigadier-completions: true
  packet-limiter:
    kick-message: '&cSent too many packets'
    limits:
      all:
        interval: 7.0
        max-packet-rate: 500.0
      PacketPlayInAutoRecipe:
        interval: 4.0
        max-packet-rate: 5.0
        action: DROP
messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
  kick:
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
    authentication-servers-down: ''
timings:
  enabled: true
  verbose: true
  url: https://timings.aikar.co/
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  - settings.velocity-support.secret
  history-interval: 300
  history-length: 3600
  server-name: Unknown Server
world-settings:
  default:
    seed-based-feature-search: true
    seed-based-feature-search-loads-chunks: true
    map-item-frame-cursor-update-interval: 10
    update-pathfinding-on-block-update: true
    allow-player-cramming-damage: false
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    filter-nbt-data-from-spawn-eggs-and-related: true
    disable-creeper-lingering-effect: false
    baby-zombie-movement-modifier: 0.5
    max-auto-save-chunks-per-tick: 24
    count-all-mobs-for-spawning: false
    use-vanilla-world-scoreboard-name-coloring: false
    prevent-moving-into-unloaded-chunks: false
    disable-thunder: false
    disable-ice-and-snow: false
    keep-spawn-loaded-range: 10
    show-sign-click-command-failure-msgs-to-player: false
    prevent-tnt-from-moving-in-water: false
    iron-golems-can-spawn-in-air: false
    grass-spread-tick-rate: 1
    water-over-lava-flow-speed: 5
    use-faster-eigencraft-redstone: false
    nether-ceiling-void-damage-height: 0
    allow-non-player-entities-on-scoreboards: false
    fix-items-merging-through-walls: false
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    fix-climbing-bypassing-cramming-rule: false
    armor-stands-do-collision-entity-lookups: true
    skeleton-horse-thunder-spawn-chance: 0.01
    container-update-tick-rate: 1
    portal-search-radius: 128
    portal-create-radius: 16
    portal-search-vanilla-dimension-scaling: true
    keep-spawn-loaded: true
    only-players-collide: false
    allow-vehicle-collisions: true
    max-leash-distance: 10.0
    map-item-frame-cursor-limit: 128
    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
    entities-target-with-follow-range: false
    spawner-nerfed-mobs-should-jump: false
    zombies-target-turtle-eggs: true
    zombie-villager-infection-chance: -1.0
    light-queue-size: 20
    auto-save-interval: -1
    armor-stands-tick: true
    delay-chunk-unloads-by: 10s
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 1
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    per-player-mob-spawns: true
    disable-teleportation-suffocation-check: false
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    fix-wither-targeting-bug: false
    allow-using-signs-inside-spawn-protection: false
    ender-dragons-death-always-places-dragon-egg: false
    max-entity-collisions: 8
    piglins-guard-chests: true
    should-remove-dragon: false
    optimize-explosions: false
    remove-corrupt-tile-entities: false
    fixed-chunk-inhabited-time: -1
    experience-merge-max-value: -1
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    hopper:
      cooldown-when-full: true
      disable-move-event: false
    spawn-limits:
      monsters: -1
      animals: -1
      water-animals: -1
      water-ambient: -1
      ambient: -1
    mobs-can-always-pick-up-loot:
      zombies: false
      skeletons: false
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 75
    door-breaking-difficulty:
      zombie:
      - HARD
      vindicator:
      - NORMAL
      - HARD
    entity-per-chunk-save-limit:
      experience_orb: -1
      snowball: -1
      ender_pearl: -1
      arrow: -1
      fireball: -1
      small_fireball: -1
    game-mechanics:
      scan-for-legacy-ender-dragon: true
      disable-end-credits: false
      disable-unloaded-chunk-enderpearl-exploit: true
      disable-relative-projectile-velocity: false
      disable-pillager-patrols: false
      disable-chest-cat-detection: false
      nerf-pigmen-from-nether-portals: false
      disable-sprint-interruption-on-attack: false
      shield-blocking-delay: 5
      disable-player-crits: false
      disable-mob-spawner-spawn-egg-transformation: false
      fix-curing-zombie-villager-discount-exploit: true
      pillager-patrols:
        spawn-chance: 0.2
        spawn-delay:
          per-player: false
          ticks: 12000
        start:
          per-player: false
          day: 5
    feature-seeds:
      generate-random-seeds-for-all: false
    viewdistances:
      no-tick-view-distance: -1
    anti-xray:
      enabled: false
      engine-mode: 1
      max-block-height: 64
      update-radius: 2
      lava-obscures: false
      use-permission: false
      hidden-blocks:
      - copper_ore
      - deepslate_copper_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - coal_ore
      - deepslate_coal_ore
      - lapis_ore
      - deepslate_lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - deepslate_diamond_ore
      - redstone_ore
      - deepslate_redstone_ore
      - clay
      - emerald_ore
      - deepslate_emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - oak_planks
      - deepslate
    generator-settings:
      flat-bedrock: false
    unsupported-settings:
      fix-invulnerable-end-crystal-exploit: true
    squid-spawn-height:
      maximum: 0.0
    mob-effects:
      undead-immune-to-certain-effects: true
      spiders-immune-to-poison-effect: true
      immune-to-wither-effect:
        wither: true
        wither-skeleton: true
    alt-item-despawn-rate:
      enabled: false
      items:
        COBBLESTONE: 300
    tick-rates:
      sensor:
        villager:
          secondarypoisensor: 40
      behavior:
        villager:
          validatenearbypoi: -1
    despawn-ranges:
      soft: 32
      hard: 128
    max-growth-height:
      cactus: 3
      reeds: 3
      bamboo:
        max: 16
        min: 11
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
