plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom-remap'
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")
    modImplementation("maven.modrinth:modmenu:11.0.4")
    modImplementation("curse.maven:jei-238222:7420583")
}

loom {
    def clientRunDirectory = layout.projectDirectory.dir('runs/client')
    def serverRunDirectory = layout.projectDirectory.dir('runs/server')

    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            displayName.set('Fabric Client')
            generateRunConfig.set(true)
            runDirectory.set(clientRunDirectory)
        }

        server {
            server()
            displayName.set('Fabric Server')
            generateRunConfig.set(true)
            runDirectory.set(serverRunDirectory)
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'modCompileClasspath'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
loom.remapConfigurations.configureEach {
    configurations.named(it.name) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
