# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=3.2.1.0
group=com.org.alextronstudios.betterbeaconeffects
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Better Beacon Effects
mod_author=Versel
mod_id=betterbeaconeffects
license=CC0-1.0
credits=
description=This mod brings back the beacon from the 1.4.2 snapshot 12w36a.\nThis mod also adds different effects that can be applied to the beacon by placing a block next to it.
minecraft_version_range=[1.21.1, 1.21.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.1.233
neoforge_loader_version_range=[4,)

# The version of the Parchment mappings
parchment_version = 2024.11.17

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
